# Generated by Django 2.1.3 on 2018-12-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=150, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('invoice', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('FQDN', models.CharField(max_length=50, null=True)),
                ('datetime', models.DateField()),
                ('form', models.CharField(max_length=50, null=True)),
                ('bios', models.CharField(max_length=50, null=True)),
                ('prod', models.CharField(max_length=50, null=True)),
                ('vendor', models.CharField(max_length=50, null=True)),
                ('OS', models.CharField(max_length=50, null=True)),
                ('kernel', models.CharField(max_length=50, null=True)),
                ('CPU', models.CharField(max_length=50, null=True)),
                ('cores', models.CharField(max_length=50, null=True)),
                ('arch', models.CharField(max_length=50, null=True)),
                ('mem', models.CharField(max_length=50, null=True)),
                ('HDD', models.CharField(max_length=50, null=True)),
                ('disk', models.CharField(max_length=50, null=True)),
                ('diskfree', models.CharField(max_length=50, null=True)),
                ('IPs', models.CharField(max_length=50, null=True)),
                ('gateway', models.CharField(max_length=50, null=True)),
                ('gate_iface', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.Device')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Machine')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='komp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.Machine'),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.DeviceType'),
        ),
    ]
