# Generated by Django 2.1.7 on 2019-04-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20181202_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
