# Generated by Django 2.2.5 on 2019-09-21 18:15

from django.db import migrations, models
import machines.models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_auto_20190921_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to=machines.models.device_upload_location),
        ),
    ]
