# Generated by Django 3.0.14 on 2022-01-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_device_invoice_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
