# Generated by Django 3.2 on 2022-02-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_auto_20220131_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-is_active', 'FQDN']},
        ),
        migrations.AddField(
            model_name='machine',
            name='dist_major_ver',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
