# Generated by Django 2.1.7 on 2019-04-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_device_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
