# Generated by Django 2.1.7 on 2019-04-13 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_auto_20190413_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='datetime',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='device',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='machines.Machine'),
        ),
    ]
