# Generated by Django 2.1.3 on 2018-12-14 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_auto_20181122_1649'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=35, null=True, verbose_name='nazwa firmy')),
                ('name', models.CharField(max_length=35, null=True, verbose_name='imię i nazwisko')),
                ('street', models.CharField(blank=True, max_length=35, null=True, verbose_name='ulica')),
                ('city', models.CharField(blank=True, max_length=35, null=True, verbose_name='miasto')),
                ('tax_id', models.CharField(blank=True, help_text='tylko cyfry', max_length=35, null=True, unique=True, verbose_name='NIP')),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=35, null=True, verbose_name='telefon')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'klient',
                'verbose_name_plural': 'klienci',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=35, verbose_name='numer faktury')),
                ('issued', models.DateField(verbose_name='data wystawienia')),
                ('transaction', models.DateField(verbose_name='data sprzedaży')),
                ('due', models.DateField(verbose_name='termin płatności')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Customer', verbose_name='klient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='cena brutto')),
                ('vat', models.FloatField(default=23, help_text='%')),
                ('qty', models.FloatField(default=1, verbose_name='ilość')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Make', verbose_name='towar')),
            ],
        ),
    ]
