# Generated by Django 2.1.3 on 2018-12-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoiceitem_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='issue_place',
            field=models.CharField(choices=[('1', 'Ustroń'), ('2', 'Wisła'), ('3', 'Cieszyn')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.CharField(choices=[('1', 'gotówka'), ('2', 'karta'), ('3', 'przelew')], default='1', max_length=1),
        ),
    ]
