# Generated by Django 2.1.3 on 2018-12-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20181221_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='vat',
            field=models.FloatField(default=23),
        ),
    ]
