# Generated by Django 2.1.3 on 2018-11-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='active',
            new_name='is_active',
        ),
    ]
