# Generated by Django 2.1.3 on 2018-12-25 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20181122_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='net_prices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='net_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(11000)], verbose_name='cena netto'),
        ),
    ]
