# Generated by Django 2.1.5 on 2019-01-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20181225_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='aktywny'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='net_prices',
            field=models.BooleanField(default=False, verbose_name='w cenach netto'),
        ),
    ]
