# Generated by Django 2.1.3 on 2018-12-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20181204_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionfile',
            options={'verbose_name': 'paczka przelewów', 'verbose_name_plural': 'paczki przelewów'},
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='tax_id',
            field=models.CharField(max_length=35, null=True, unique=True, verbose_name='NIP'),
        ),
    ]
