# Generated by Django 2.1.3 on 2018-12-04 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0003_auto_20181204_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account', models.CharField(max_length=34, verbose_name='numer konta')),
                ('comment', models.CharField(max_length=50, verbose_name='komentarz')),
            ],
            options={
                'verbose_name': 'konto bankowe',
                'verbose_name_plural': 'konta bankowe',
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='counterpartyaccount',
            name='counterparty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.Counterparty', verbose_name='kontrahent'),
        ),
        migrations.AddField(
            model_name='counterpartyaccount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
