# Generated by Django 2.1.3 on 2018-12-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20181204_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfile',
            name='transaction',
            field=models.ManyToManyField(to='transactions.Transaction'),
        ),
    ]
