# Generated by Django 2.1.3 on 2018-12-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20181204_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterpartyaccount',
            name='account',
            field=models.CharField(max_length=34, unique=True, verbose_name='numer konta'),
        ),
    ]
