# Generated by Django 2.1.3 on 2018-12-07 15:02

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20181207_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterpartyaccount',
            name='account',
            field=models.CharField(max_length=26, unique=True, validators=[django.core.validators.MinLengthValidator(26), django.core.validators.MaxLengthValidator(26), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None)], verbose_name='numer konta'),
        ),
    ]
