# Generated by Django 2.1.3 on 2018-12-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20181213_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='counterparty_account',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ordering_account',
            field=models.CharField(max_length=26),
        ),
    ]
