# Generated by Django 2.1.3 on 2018-12-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20181213_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='counterparty_bank',
        ),
    ]
