# Generated by Django 2.1.3 on 2018-12-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_remove_transaction_counterparty_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='execution_date',
            field=models.DateField(verbose_name='data wykonania'),
        ),
    ]
