# Generated by Django 2.1.3 on 2018-12-13 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20181213_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbanValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=26, unique=True, validators=[django.core.validators.MinLengthValidator(26), django.core.validators.MaxLengthValidator(26)], verbose_name='numer konta')),
            ],
            options={
                'verbose_name_plural': 'konta własne',
                'verbose_name': 'konto własne',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(default=110),
        ),
    ]
