# Generated by Django 2.1.3 on 2018-12-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_orderingaccount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.TransactionStatus'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_classification',
            field=models.CharField(choices=[('51', 'for trans type 110, 120'), ('53', 'Split Payment'), ('01', 'for trans type 210'), ('71', 'for trans type 110 (przelew US)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('110', 'polecenie przelewu (w tym US i ZUS)'), ('210', 'polecenie zapłaty'), ('510', 'polecenie przelewu SORBNET')], max_length=3),
        ),
    ]
