# Generated by Django 2.1.3 on 2018-12-21 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20181213_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='counterparty_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.CounterpartyAccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ordering_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.OrderingAccount'),
        ),
    ]
