# Generated by Django 2.1.3 on 2018-12-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_auto_20181221_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='counterparty_account_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ordering_account_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='counterparty_account_text',
            field=models.CharField(default='', max_length=26),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ordering_account_text',
            field=models.CharField(default='', max_length=26),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.CounterpartyAccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ordering_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.OrderingAccount'),
        ),
    ]
