# Generated by Django 2.1.3 on 2018-12-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_auto_20181221_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ordering_name_address_text',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ordering_name_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.Counterparty'),
        ),
    ]
