# Generated by Django 2.1.3 on 2018-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20181221_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ordering_name_address_text',
        ),
        migrations.AddField(
            model_name='orderingaccount',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ordering_name_address',
            field=models.CharField(default='', max_length=150),
        ),
    ]
