# Generated by Django 2.1.3 on 2018-12-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_auto_20181221_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingaccount',
            name='comment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orderingaccount',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
