# Generated by Django 2.1.3 on 2018-12-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20181221_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_title',
            field=models.CharField(max_length=140, verbose_name='tytuł'),
        ),
    ]
