# Generated by Django 2.1.5 on 2019-01-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_auto_20181221_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IbanValidator',
        ),
    ]
